### ISSUE TITLE
その他ラジオが，うまく動かせない。

### ISSUE THREAD

**Issue by keii3** [kodiful/plugin.audio.kodi.ra#2]
kodi v19.0 for Mac + plugin.audio.kodi.ra 7.0.2にて，「その他ラジオ」で局を追加した際，以下のエラーが発生，「その他ラジオ」が動作しません。

<pre>
021-03-22 11:35:35.021 T:88526   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: read_file() got an unexpected keyword argument 'mode'
                                                   Traceback (most recent call last):
                                                     File "/Users/keii3/Library/Application Support/Kodi/addons/plugin.audio.kodi.ra/default.py", line 130, in <module>
                                                       Cache().clearData()
                                                     File "/Users/keii3/Library/Application Support/Kodi/addons/plugin.audio.kodi.ra/default.py", line 74, in clearData
                                                       self.update()
                                                     File "/Users/keii3/Library/Application Support/Kodi/addons/plugin.audio.kodi.ra/default.py", line 41, in update
                                                       self.update_classes(renew)
                                                     File "/Users/keii3/Library/Application Support/Kodi/addons/plugin.audio.kodi.ra/resources/lib/service.py", line 95, in update_classes
                                                       self.programs = Programs((self.radiru, self.radiko, self.jcba, self.misc))
                                                     File "/Users/keii3/Library/Application Support/Kodi/addons/plugin.audio.kodi.ra/resources/lib/programs.py", line 86, in __init__
                                                       logopath = self.__save_logo(data['id'], data.get('logo_large'))
                                                     File "/Users/keii3/Library/Application Support/Kodi/addons/plugin.audio.kodi.ra/resources/lib/programs.py", line 114, in __save_logo
                                                       buffer = read_file(Const.LOGO_FILE, mode='rb')
                                                   TypeError: read_file() got an unexpected keyword argument 'mode'
                                                   -->End of Python script error report<--
                                                   
</pre>

また，settings.xmlに局の情報が追記されていない様です。

**Comment by kodiful** [comment]
Kodi 19対応の修正漏れでした。この不具合に関連して、指定したURLのロゴ画像が取得できない不具合も見つかったので、合わせて修正し、7.0.3としました。ご確認ください。

**Comment by keii3** [comment]
早速の対応，ありがとうございます。
7.0.3に差し替えた所，エラーは発生せず，正しく動作させる事が出来ました。
また，ロゴ画像の取得も正しく行われる事も確認しました。
